"""followers

Revision ID: 095acb6888ef
Revises: 4947572fa878
Create Date: 2018-02-28 09:32:42.590846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095acb6888ef'
down_revision = '4947572fa878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
